### ISSUE TITLE
Compatibility with scikit-learn 0.19

### ISSUE THREAD

**Issue by jimmywan** [dask/dask-searchcv#54]
Does dask-searchcv work with scikit-learn 0.19+? Getting the following error
```
  File "/home/vagrant/.pyenv/versions/miniconda3-4.1.11/envs/gambit/lib/python3.6/site-packages/dask_searchcv/methods.py", line 16, in <module>
    from sklearn.utils.fixes import rankdata
ImportError: cannot import name 'rankdata'
```

**Comment by jcrist** [comment]
This was fixed in #53. Can you install from master?

```
pip install git+https://github.com/dask/dask-searchcv.git
```

I'll probably push a release in the next few days.

**Comment by TomAugspurger** [comment]
Although it looks like we use `sklearn.utils.fixes.in1d` in https://github.com/dask/dask-searchcv/blob/63e450d0ae61078ef89297ccdcf0a2d90e9d4430/dask_searchcv/tests/test_model_selection_sklearn.py#L32, which was also remove

**Comment by jcrist** [comment]
That's just a test, but good catch, will fix.

**Comment by jcrist** [comment]
> That's just a test, but good catch, will fix.

Fixed in #55. I plan to release sometime later this week.

**Comment by jimmywan** [comment]
Thanks @jcrist . Fixes seem to allow execution again. Still running into #28 though. Commented over there since my error seems to be the same as pre scikit-learn 0.19.

**Comment by jcrist** [comment]
Just released `dask-searchcv` version `0.1.0`, which is compatible with scikit-learn `0.19.0`. Available on pypi and conda-forge.

I think this issue can be closed now, feel free to reopen/open a new issue if you continue to have problems.
